### PR TITLE
issue 173: removing puzzle

### PR DESCRIPTION
**Pull request by YamStranger**
issue #173: removing puzzle

all fixes and descriptions provided under PR #183 and #184 . This is final pull request, I hope

### CODE REVIEW

**Comment by YamStranger** [comment]
@dmarkov please assign to reviewer. Thanks

**Comment by dmarkov** [comment]
@yamstranger Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by dmarkov** [comment]
> @dmarkov please assign to reviewer. Thanks

@yamstranger np ;)

**Comment by yegor256** [comment]
@rultor merge it pls

**Comment by dmarkov** [comment]
@yegor256 **16 mins** was added to your account, many thanks for your contribution (payment 000-c5787d8f)! The task took 24 hours and 53 mins.. extra minutes for review comments (c=1). +16 added to your rating, current score is: [+13590](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
