### PR TITLE
210

### LINKED ISSUE #210: How to use Gradle for plugin
How do i use with gradle for Loggable annotation

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #210 

@yegor256 take a look, please

### CODE REVIEW

**Comment by andreoss** [comment]
@l3r8yJ 
Could you rebase onto master? 
Where will this page appear?

**Comment by l3r8yJ** [comment]
@andreoss @yegor256 can someone start workflows?

**Comment by l3r8yJ** [comment]
@andreoss @yegor256 I suppose that page will appear in `Examples` section; also I've added puzzle about integration test

take a look, please

**Comment by yegor256** [comment]
@l3r8yJ thanks!

**Pull request merged**
