### PR TITLE
Update annotation-timeable.html

### PR DESCRIPTION
**Pull request by sfat**
Corrected Thread.currentThread() call

### CODE REVIEW

**Comment by dmarkov** [comment]
@sfat Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@sfat don't change anything in gh-pages branch. The content there is auto-generated. Change source code in `src` directory.

**Comment by dmarkov** [comment]
@yegor256 I added **17 mins** to your account, many thanks for working with the project! The completion time here was 000-2c911ae7.; you're getting extra minutes here (c=2); +17 added to your rating, current score is: [+11998](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
