### PR TITLE
make jcabi-aspects a valid OSGI bundle

### PR DESCRIPTION
**Pull request by gdelafosse**
use the maven-bundle-plugin to make jcabi-aspects a valid OSGI bundle

### CODE REVIEW

**Comment by dmarkov** [comment]
@gdelafosse Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 Thanks for your contribution, **16 mins** was added to your account, payment ID is `000-f771b7d1`, 18 hours and 59 mins spent total. extra minutes for review comments (c=1). +16 to your rating, your total score is [+6774](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
