### PR TITLE
Tv(time values) shouldn't be a Constants Interface

### PR DESCRIPTION
**Pull request by simonjenga**
#160 Tv(time values) shouldn't be a Constants Interface

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@longtimeago please review this PR

**Comment by longtimeago** [comment]
@rultor merge

**Comment by yegor256** [comment]
@simonjenga what is a motivation for this change?

**Comment by simonjenga** [comment]
@yegor256  @longtimeago 
The constant interface pattern is a poor use of interfaces. interfaces should deal with the services provided by an object, not its data.

I am not an expert on this issue but the following links will help in expounding on the topic.

http://en.wikipedia.org/wiki/Constant_interface

http://www.coderanch.com/t/521414/java/java/Declaring-constants-class-Declaring-interface

http://stackoverflow.com/questions/320588/interfaces-with-static-fields-in-java-for-sharing-constants

https://javax0.wordpress.com/2013/10/31/defining-constants-in-an-interface/

http://www.javapractices.com/topic/TopicAction.do?Id=32

http://programmers.stackexchange.com/questions/49572/is-it-a-bad-practice-to-have-an-interface-to-define-constants

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@longtimeago I added **16 mins** to your account, many thanks for working with the project! The completion time here was 59134040.; review comments (c=1) added as a bonus; +16 added to your rating, current score is: [+3787](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
