### PR TITLE
Update annotation-timeable.html

### PR DESCRIPTION
**Pull request by sfat**
Corrected Thread.currentThread() call

### CODE REVIEW

**Comment by dmarkov** [comment]
@sfat Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 I added **16 mins** to your account, many thanks for working with the project! The completion time here was 000-5a3b5b24.... review comments (c=1) added as a bonus... +16 added to your rating, at the moment it is: [+9750](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
