### PR TITLE
#123 - fixed copyright section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@krzyk please review this one

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk Much appreciated! **16 mins** was added to your account, payment ID `50300547`... +16 added to your rating, at the moment it is: [+1663](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
