### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Thanks a lot, I just topped your account for **16 mins**, transaction ID `000-26ea6362`, total time was 20 hours and 44 mins... you're getting extra minutes here (c=1)... +16 added to your rating, at the moment it is: [+4271](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
