### PR TITLE
#118 added check for immutability for actual classes in addition to declared

### PR DESCRIPTION
**Pull request by darkled**

### CODE REVIEW

**Comment by darkled** [comment]
@longtimeago done, please, check it again

**Comment by longtimeago** [comment]
@rultor please merge

**Comment by dmarkov** [comment]
@longtimeago Thanks a lot, I just topped your account for **18 mins**, transaction ID `49904061`. +18 to your rating, your total score is [+1088](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
