### PR TITLE
CacheableTest.java:57-58: Make sure that this test... #133

### PR DESCRIPTION
**Pull request by nhekfqn**

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks, I'll find someone to review it before we merge

**Comment by dmarkov** [comment]
@krzyk review this one please

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk Thanks a lot, I just topped your account for **15 mins**, transaction ID `51611916`

added +15 to your rating, now it is equal to [+3975](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
