### PR TITLE
issue 194

### PR DESCRIPTION
**Pull request by olegsimanov**

### CODE REVIEW

**Comment by dmarkov** [comment]
@olegsimanov Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@dmzaytsev this pull request is for you, please review

**Comment by dmzaytsev** [comment]
@olegsimanov CI builds failed
let's fix it

**Comment by dmzaytsev** [comment]
@olegsimanov according our [quality rules](www.teamed.io/qa.html)

> Pull request title explains the problem it is fixing.

> Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

**Comment by dmzaytsev** [comment]
@olegsimanov ping

**Comment by dmzaytsev** [comment]
@olegsimanov please close pull request if you don't want to work on it anymore

**Comment by dmarkov** [comment]
@dmzaytsev **19 mins** sent to your balance (ID `73489358`), many thanks! It took 434 hours and 59 mins.. extra minutes for review comments (c=4). +19 added to your rating, current score is: [+1258](http://www.netbout.com/b/35166?open=rating)

**Pull request closed without merging**
