### PR TITLE
added .gitattributes file for Unix-like end of line

### PR DESCRIPTION
**Pull request by simonjenga**
#161 added .gitattributes file for Unix-like end of line

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@yegor256 Much obliged! I have added **16 mins** to your account in payment "000-e9c5c1f3", 23 hours and 1 min spent. review comments (c=1) added as a bonus. added +16 to your rating, now it is equal to [+6665](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
