### PR TITLE
Added in capability for infinite retries with @RetryOnFailure

### PR DESCRIPTION
**Pull request by csmartin1024**

### CODE REVIEW

**Comment by dmarkov** [comment]
@csmartin1024 Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@dmzaytsev it's yours, please review

**Comment by dmzaytsev** [comment]
@csmartin1024  please add description of what you did in the PR description, also include there reference to the issue you are fixing

**Comment by dmzaytsev** [comment]
@csmartin1024 also you have a few checkstyle issues, see  AppVeyor or Travis CI build log
please fix it

btw you can run locally
> mvn clean install -Pqulice 

to force Qulice checks

**Comment by dmzaytsev** [comment]
@csmartin1024 ping

**Comment by dmzaytsev** [comment]
@csmartin1024 if you don't want continue with this PR please close it

**Comment by csmartin1024** [comment]
There was no issue. Was adding features

**Comment by dmarkov** [comment]
@dmzaytsev Thank you, I have added **19 mins** to your account in payment/transaction "`76661000`", time consumed: 236 hours and 59 mins... extra minutes for review comments (c=4)... +19 added to your rating, current score is: [+3043](http://www.netbout.com/b/35166?open=rating)

**Pull request closed without merging**
