### PR TITLE
#131 - Immutable tests

### PR DESCRIPTION
**Pull request by maurezen**
Deleted the tests in question as per discussion in #132

### CODE REVIEW

**Comment by maurezen** [comment]
@dmarkov please find someone to review this pull request.

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@krzyk could you please review this pull request

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by krzyk** [comment]
@yegor256 please try again, looks like timing issue in test for `Loggable`

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk I just added **15 mins** to your account, many thanks for your contribution..... +15 added to your rating, current score is: [+3912](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
